### PR TITLE
Imgui update

### PR DESCRIPTION
**Pull request by JonnyPtn**
Let's try this again...

Updated ImGui to 1.54
Added autocomplete addressing #8 
Slight refactor of current gui stuff - Console, video, and audio settings are all in the same window, on different tabs. Status controls are added as their own tabs, and some other shuffling around.

Tested with the demo here and it works great, would suggest testing your end too though.

screenie

### CODE REVIEW

**Comment by fallahn** [comment]
Fails to build on linux :( Needs cstdint / stdint.h included in imgui_tabs.cpp, maybe also let the author know?

**Comment by fallahn** [comment]
Builds fine with visual studio, just needed to update the included project with the new files. imgui_tabs.cpp also defines `_CRT_SECURE_NO_WARNINGS` which should probably be a project level definition, and only for MSVC. VS complains that it's a double definition because it's also defined by the xygine project.

Looks good though, thanks! The only other thing I might say (and this is a niggle) is that the combobox for video resolution doesn't select the current resolution any more. Oh and the status window which you used to open with F2 needs to remain separate - it's meant for updating real time stats and trying to send them to the console just spams the window with debug messages. Try loading the first map in a debug build and you'll see what I mean :)

**Comment by JonnyPtn** [comment]
I've put the debug lines back in their own tab. I've noticed the lines flicker due to the order ImGui is processed in, but as far as I can tell it was that way before :S ?

Also removed the double define and added missing linux include

**Comment by fallahn** [comment]
Awesome, thanks! Yeah the flickering is due to the occasional double update because of the fixed timestep - best I could get it without refactoring the entire game loop.

**Comment by JonnyPtn** [comment]
I've added wrappers for ImGui::GetIO().wantCaptureKeyboard and ImGui::GetIO().wantCaptureMouse, and used them in the demo menu state

**Comment by fallahn** [comment]
Good stuff! I'll test it out when I get home and hopefully merge it.

**Pull request merged**
