### PR TITLE
Initial implementation of handle based resource management

### PR DESCRIPTION
**Pull request by JonnyPtn**
A first draft of an alternative to the current resource management. The drive behind this was to firstly create a system based around handles to make serialising components (and therefore serialising scenes) possible, and secondly to have one system to manage all types of resources

You must explicitly load the resource with `load<type>(path)` which returns a handle. You can then use that handle to access the resource with `get<type>(handle)`.

There is also functionality fo the user to add their own type of resource, by adding a `ResourceLoader`. For an example see the constructor of `ResourceHandler` where I've added the default loaders for `sf::Texture` and `sf::Font`.

This doesn't have any effect on the existing resource management, as you can see I've left the Demo mostly as is, just modifying the Menu State to use this method of resource handling as an example.

This does make use of std::any, so c++17 is required. ~~I haven't made this change in the CMakeLists, but I've added some macros which should emit a compiler error if someone tries to use `ResourceHandler` without c++17 enabled.~~ This didn't work as intended, so c++17 is an hard requirement unless I can work some way around it - Something to think about...

Only a first draft, so completely open to feedback/changes

### CODE REVIEW

**Comment by fallahn** [comment]
This looks really good! I like the interface, and it gives a nice uniform feel to resource access. My thoughts are:

- If the handle is an index then there's no reason not to just leave it as an alias for `std::size_t` I think
- Regarding the getter/setter for loaders it's probably fine as is, maybe needs a const ref overload for it?
- You have my name in the copyright line instead of yours ;)
- Shaders are a slightly different case when it comes to management (see the existing ShaderResource) because I tend to use inline source code rather than load from file - plus shaders can be loaded from multiple sources if they contain say both a vertex and fragment shader. I think this can be worked around by using parameter packing and forwarding the `load()` parameters to the coressponding loader, but I'm not sure how to differenciate between source code strings and path strings - additional enum value perhaps?
- Also probably not worth passing `ResourceHandle` as a const reference when a copy will do :)

As for C++17 requirements - I'm fine with this, having to use `<experimental>` in some places niggles me a bit but I guess I can live with it for the immediate future. I've tested any/optional with VS and g++8 and had no problems so I'm guessing it's just apple not quite caught up yet?

**Comment by JonnyPtn** [comment]
Yeah it's just Apple which is behind on the "experimental" stuff. Hoping this will be sorted out in Xcode 10 which should be released soon.

I've made all the changes you mentioned, although can't work out a way to get shaders playing nicely with it. I tried doing some parameter packing magic but couldn't get it to work, I think because there's no way for the `std::function` member of`ResourceLoader`  to have templated parameters. I think to get this working we'd need to make it a virtual class which users then override a `template<class... Args> load(Args... args)` but my experience with this stuff is quite limited so maybe you have the magic touch on it...

Also the windows CI is kicking off about the embedded default font I've used being undefined, not sure why... do you get that error?

**Comment by fallahn** [comment]
I've thought long and hard about this and tried a few tests but nothing really seems to fit. I took a step back to think about exactly what's trying to be achieved with shaders - and the main problem is that they simply aren't a resource to be loaded from disk like other resources are. Even the simplest version loaded from a single file requires a flag stating whether or not it's a source file for a vertex or fragment shader, and things escalate quickly once you try to load multiple shaders sources from file, memory or otherwise. I think that for these same reasons it'll be tricky to manage shaders in the editor in general - how are shaders edited? How are they referenced by components that use them etc? For now I think that we should put shaders aside as they'll require their own special treatment and then work on managing them later - I have a few ideas about the possibility of pre-processing shaders via the editor and saving them as a special file containing all the shader source and some kind of description header (shaders types, perhaps available uniforms etc) which can be used as a resource, but I need to put a bit more thought into how that'll work.

**Comment by JonnyPtn** [comment]
Yeah I'm perfectly happy with putting shaders to one side for now, I'd been partly avoiding them from an editor point of view for those same reasons... The existing shaderResource can still be used until an alternative is found/needed

**Comment by JonnyPtn** [comment]
Just a few workarounds needed for Apple, annoyingly... - first use the `stdx` namespace hack to work around experimental folder issue.

Also seems the current Mac implementation doesn't have `make_any`. I think this can be solved by changing that line to `stdx::any tex = sf::Texture();`? This works for me, so if it works for you then everything else is fine

**Comment by JonnyPtn** [comment]
Having tested this in Xcode 10 beta, where std::any is correctly implemented and in all the right places, I'm half tempted to say let's leave this until that's released...

**Comment by fallahn** [comment]
Yeah I agree - I'd rather wait than write workarounds which would eventually get removed anyway

**Comment by fallahn** [comment]
Haven't forgotten about this - and I see green lights! Is this ready to merge?

**Comment by JonnyPtn** [comment]
I'd say so yeah. I could probably squash the commits to tidy up the history if you'd like?

A few notes worth reminding about:
- This will enforce c++17 usage (then also Xcode 10 on macOS)
- The default embedded font (dejavusans) is a bit of a whopper. Not really an issue until you open the file, but might want to consider a better alternative in future, this can always be done at a later date.
- There's some less-than-ideal code duplication in classes which require a resource manager/handler (e.g. spritesheet). I just duplicated the methods to go the route of least resistance but ideally we'd have a better way to handle this

**Comment by fallahn** [comment]
Excellent! Just to address the points:

- I've actually been wanting to implement some other C++17 stuff but holding off for this PR, so awesome :)
- Yes, yes it is. That's always been at the back of my mind but I tend to forget about it until I try to open the file. This should probably have an issue raised for it
- To be honest, I hadn't noticed :) I'll give the entire PR a run through with VS tonight, make some notes then hopefully merge it.

Thanks!

**Pull request merged**
