### PR TITLE
macOS app bundling

### PR DESCRIPTION
**Pull request by JonnyPtn**
This changes the CMakeLists for the demo to create a macOS app bundle, and the required changes to code in xyginext and the demo to get the correct path to the resource folder within said bundle.

I pondered for a while whether it should be xyginext or the game which prepends the bundle resource path when loading, and ended up at some sort of compromise:

 - xyginext implements `xy::FileSystem::getResourcePath()` which returns the path to the Resources folder within the app bundle (or an empty string if not in an app bundle)
- xyginext resources will automatically prepend the resource path, other classes won't (including other filesystem functions)

As a greasy little bonus, the "package" target should create a tidy little dragndrop installer on OSX, which is the most widely used and familiar installation method.

### CODE REVIEW

**Comment by fallahn** [comment]
Works perfectly! Not really my area (as you know) but aren't external dylibs supposed to be packaged in a frameworks directory inside the bundle? I can only see the resources in my build

**Comment by JonnyPtn** [comment]
Yeah, I'm still fiddling with how dependencies are handled. The calls to verify_bundle and fixup_bundle should verify and fixup the bundle, but I think there's some funniness whereby if the dependencies are installed in a system path (e.g. /usr/local/) It will assume they are system dependencies, and therefore won't include them in the bundle.

I've just noticed those two calls are in the package target, so I'll move them into the build stage. In the meantime if you try building the package target, see if that bungs anything extra in the bundle before generating the installer. If nothing else you should see the output from verify/fixup_bundle if there are any warnings/errors

**Comment by JonnyPtn** [comment]
OK, I've been playing around with various incantations of this, and I've come to the conclusion that this implementation is the best of a bad bunch, it just has some quite specific conditions:

- Xcode generator **must** be used for bundling to work correctly (this may be fixable in future)
- Building the default target (all) will generate the bundle, but will not copy any dependencies into it
- Building the install target will call fixup_bundle and verify_bundle, and will copy the dependencies into the bundle. I've sometimes had this throw errors when xyginext or tmxlite are installed to system directories (for some reason the sgml libs installed via brew work fine and are bundled correctly), so if you get errors first try installing them to a non-standard path
- Building the package target will generate the dragndrop installer for distribution. For some reason I can't explain it still includes the "assets" folder even though it's precluded from the install target :S

I'm going to add a variable to the CMakeLists to toggle bundling, as it has some peculiarities which may be a burden to your average user, but it can achieve an entirely portable bundle so will hopefully be useful for people who want that

**Comment by fallahn** [comment]
Awesome, this sounds good, certainly for what I want it to do at least :) I think as long as it's documented such as on the build info page on the wiki then most people will be OK. Will test it out as soon as I can.

**Comment by fallahn** [comment]
I updated the cmake file with rpath settings so bundling now correctly finds tmxlite/xygine. I also changed the install directory of the bundle so that it doesn't need admin privileges (I think that's OK). Could get it to copy the assets folder though...

**Comment by JonnyPtn** [comment]
This is working great for me here - were you using the Xcode generator? I seem to remember using makefiles meant the assets weren't copied.

I'm just updating the travis config to build the bundle and package, to hopefully verify all this

**Comment by fallahn** [comment]
Using the Xcode generator followed by `cmake --build . --target install` . Maybe missed something else?

**Comment by JonnyPtn** [comment]
hrm, nope that's exactly what I'm doing too

**Comment by fallahn** [comment]
Just tried on a clean install... I don't get any bundle at all now, instead it copies the assets folder and binary to /usr/lib/ ... which to me seems like CMake isn't running the mac specific part of the script :S

**Pull request merged**
