### PR TITLE
Imgui updates

### PR DESCRIPTION
**Pull request by JonnyPtn**
This updates ImGui, but does also change behaviour:

- Imgui no longer blocks input (To be honest I like this, as It means I can handle ImGui input blocking in game code)
- Anything else mentioned in the ImGui diff comments which breaks it's API (although I've fixed any issues in xygine, and currently ImGui is only exposed through nim wrapper)

I also added the (currently experimental) ImGui tabs code, for delicious things like this: 
Imgur

### CODE REVIEW

**Comment by fallahn** [comment]
The problem with it not consuming events is that when you click on an open window you're effectively clicking on the gameworld behind it too, which may not be desirable

**Comment by fallahn** [comment]
I had to revert this - when opening an ImGui window all SFML rendering stops working (the game screen goes black) apart from a green rectangle where the window was once it's closed

**Comment by JonnyPtn** [comment]
I think I've found this issue, my bad - I've been testing with the demo, but for some reason could only reproduce this in the menu, and not in the game state, where I'd typically test things.

Anyway, It seems that I missed a change in the Imgui-sfml API. in App.cpp, changing `ImGui::Render()` to `ImGui::SFML::Render(*getRenderWindow)` fixes it for me, can you test your end?

**Comment by fallahn** [comment]
Will test as soon as I can, thanks. I accepted the event consumption anyway because it didn't seem to break anything, so for now not a problem

**Pull request merged**
