### PR TITLE
Build system refinements

### PR DESCRIPTION
**Pull request by JonnyPtn**
After playing around with travis to get S3 deployment working, then losing my changes during some git  tomfoolery, I decided I should probably get a branch set up for this...

I have a few things in mind which I'm aiming to do (in rough order of priority):

- ~~Update appveyor to match travis config~~
- ~~Add some reliable versioning (will probably involve cmake mods too)~~
- ~~On tagged commits, upload artefacts to GitHub releases~~
- ~~use package target so an installer is created for the demo (and possibly for libs too?)~~

### CODE REVIEW

**Comment by JonnyPtn** [comment]
strong start

**Comment by JonnyPtn** [comment]
This is all updated now:

- Builds both the libs and the demo on all 3 platforms (Also threw in an iOS build for future use, which is disabled at the moment)
- To deploy a release, simply tag a commit (Or set up a release on GH) and for each platform the bots will upload a zip of the library binaries, and an installer for the demo
- I haven't been able to 100% test the uploads from travis, as the encrypted API keys are linked to the repository, so I've included an api key which should be linked to fallahn/xygine instead of JonnyPtn/xygine, which will hopefully work
- Version number is set in CMakeLists.txt, using major.minor.patch

**Comment by fallahn** [comment]
This is awesome thanks! Two things I would note: the version number is probably 0.2.0 as the legacy version is 0.1.0 (not sure it really follows semantic versioning but it made sense in my head at the time) and also from experience of shipping game / demo stuff on the likes of itch and gamejolt has taught me people don't really like installers on windows. So while the NSIS part is cool, I think it probably ought to be optional (if that's possible), favouring a zipped output.

**Comment by JonnyPtn** [comment]
No problemo, both should be fixed now.

I do still intend on setting up the automatic documentation generation and deployment, but lord knows when, so I'll leave it for a separate PR

**Comment by fallahn** [comment]
Awesome as always, thanks!

**Pull request merged**
